name: Provision Server

on:
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Secrets
        run: |
          echo "CONNECTION: '${{ secrets.SSH_CONNECTION_PROVISION }}'"

      - name: Setup SSH key for server access
        run: |
          echo "${{ secrets.SSH_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Run provision script on server
        run: |
          ssh -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.SSH_CONNECTION_PROVISION }} \
          "bash -s" < deployment/bin/provision_server/provision_server.sh ${{ secrets.MYSQL_PASSWORD }} ${{ secrets.SSH_KEY_B64 }}
